### PR TITLE
Update dependency to newer version of virtualenv

### PR DESCRIPTION
**Pull request by phtan**
This addresses problems that might occur with Python, 64-bit Ubuntu and virtualenv. The following are examples:

- [_sysconfigdata_nd.py missing in /usr/lib/python2.7/](https://bugs.launchpad.net/ubuntu/+source/python2.7/+bug/1115466/comments/8)
- [ImportError: No module named _sysconfigdata_nd](https://github.com/Strider-CD/strider/issues/336)
- [Error with _sysconfigdata_nd.py missing in /usr/lib/python2.7/ for Ubuntu 13.04 ](https://github.com/pypa/virtualenv/issues/410)

### CODE REVIEW

**Comment by jaylett** [comment]
Really we should drop using local copies of software entirely, since this was a hangover from days when we couldn't mirror pypi at all.

I'm a little worried about the "hopefully" in the PR message. Has this actually been tested? There's no point in merging this until it has.

**Comment by phtan** [comment]
Yes, it has been tested on my machine.

**Comment by phtan** [comment]
What do you mean by 'tested', though?

**Comment by phtan** [comment]
It works on my machine ('localhost', not 'live')

**Comment by jaylett** [comment]
I've eliminated bundled dependencies in 9e3335e. This may still cause problems (very old Django, for instance!), but should at least use recent pip & virtualenv so avoiding the problems you had. Feel free to open another PR if you run into problems and are able to solve them!

**Comment by phtan** [comment]
Thanks for the effort on this, @jaylett

**Pull request closed without merging**
